import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../../", import.meta.url);
const read = (relative) => readFile(new URL(relative, root), "utf8");

test("locked dependency license evidence is checked in and regenerated by CI", async () => {
  const bundle = await read("docs/licenses/RUST-DEPENDENCY-LICENSES.md");
  const ci = await read(".github/workflows/ci.yml");
  assert.match(bundle, /^# Rust runtime dependency licenses/m);
  assert.match(bundle, /ed25519-dalek/);
  assert.match(bundle, /chacha20poly1305/);
  assert.match(bundle, /sigstore-verify/);
  assert.match(bundle, /sigstore-tuf/);
  assert.match(bundle, /option-ext/);
  assert.match(ci, /cargo about generate scripts\/rust-dependency-licenses\.hbs/);
  assert.match(ci, /node scripts\/normalize-license-evidence\.mjs/);
  assert.match(ci, /grep -q 'sigstore-verify'/);
  assert.match(ci, /grep -q 'sigstore-tuf'/);
  assert.match(ci, /grep -q 'option-ext'/);
  assert.match(ci, /cmp docs\/licenses\/RUST-DEPENDENCY-LICENSES\.md/);
  assert.match(ci, /name: dependency-license-evidence-\$\{\{ github\.sha \}\}/);
  assert.match(ci, /retention-days: 3/);
  assert.doesNotMatch(ci, /retention-days:\s*(?:[4-9]|[1-9]\d+)/);
});

test("license exceptions are repository-owned reviewed expiring release evidence", async () => {
  const register = JSON.parse(await read("config/dependency-license-exceptions.json"));
  assert.equal(register.schemaVersion, 1);
  assert.ok(register.owner.length > 0);
  assert.match(register.reviewCadence, /dependency|release/i);
  assert.deepEqual(register.requiredFields, [
    "package", "license", "rationale", "approvedBy", "approvedAt", "expiresAt", "releaseLink",
  ]);
  for (const exception of register.exceptions) {
    for (const field of register.requiredFields) assert.ok(exception[field]);
    assert.ok(Date.parse(exception.expiresAt) > Date.parse(exception.approvedAt));
  }
  const ci = await read(".github/workflows/ci.yml");
  const release = await read(".github/workflows/release.yml");
  assert.match(ci, /config\/dependency-license-exceptions\.json/);
  assert.match(release, /cp config\/dependency-license-exceptions\.json release-candidate\//);
  assert.match(release, /dependency-license-exceptions\.json \\\n+\s*manifest\.json/);
});

test("every package and immutable release retain the reviewed license evidence", async () => {
  const macos = await read("scripts/package-macos.sh");
  const windows = await read("scripts/package-windows.ps1");
  const release = await read(".github/workflows/release.yml");
  for (const packaging of [macos, windows]) {
    assert.match(packaging, /docs[\\/]licenses[\\/]RUST-DEPENDENCY-LICENSES\.md/);
    assert.doesNotMatch(packaging, /cargo about generate/);
  }
  assert.match(release, /cp docs\/licenses\/RUST-DEPENDENCY-LICENSES\.md release-candidate\//);
  assert.equal(
    (release.match(/cp docs\/licenses\/RUST-DEPENDENCY-LICENSES\.md release-candidate\//g) ?? []).length,
    1,
    "the signed release candidate must materialize the reviewed license evidence once",
  );
  assert.match(release, /subject-path: release-candidate\/\*/);
  assert.match(release, /find release-candidate -mindepth 1 -maxdepth 1 -type f/);
  assert.match(release, /gh release upload "\$RELEASE_TAG" "release-candidate\/\$name"/);
  assert.match(release, /cmp expected-assets\.txt final-assets\.txt/);
});
